blank_issues_enabled: false
contact_links:
  - name: Questions or Help
    url: https://www.linkedin.com/company/giang-labs
    about: For questions, check our documentation or email us at nttg800@gmail.com
