name: bwa/index
description: Index reference genome for BWA-MEM2
keywords:
  - index
  - bwa
  - bwa-mem2
  - alignment
tools:
  - bwamem2:
      description: BWA-MEM2 is a fast and accurate aligner for long reads
      homepage: https://github.com/bwa-mem2/bwa-mem2
      documentation: https://github.com/bwa-mem2/bwa-mem2
      tool_dev_url: https://github.com/bwa-mem2/bwa-mem2
      licence: ["MIT"]

input:
  - fasta:
      type: file
      description: Input FASTA file

output:
  - index:
      type: file
      description: BWA-MEM2 index files
      pattern: "*.{0123,amb,ann,bwt.2bit.64,pac}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@giangnguyen"
